### ISSUE TITLE
Documentation: details on installation

### ISSUE THREAD

**Issue by krasheninnikov** [arnaud-ramey/rossumo#1]
Hi,
could you please provide more details on adding rossumo to the LD_LIBRARY_PATH ?

When executing this step (with my username, from .../Samples/Unix/JumpingSumoPiloting directory):

$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ardrone/sumo/out/Unix-base/staging/usr/lib ./JumpingSumoPiloting
$ sudo sh -c 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ardrone/sumo/out/Unix-base/staging/usr/lib ./JumpingSumoPiloting ' 

I get:
 ./JumpingSumoPiloting: No such file or directory

**Comment by arnaud-ramey** [comment]
Sure, I was missing the "make" step in the doc.
Commited an update.
Thanks!
