### ISSUE TITLE
missing libopencv_videostab.so when compile rossumo

### ISSUE THREAD

**Issue by kaishijeng** [arnaud-ramey/rossumo#2]
See the following error when compile rossumo:

make[2]: **\* No rule to make target `/usr/lib/x86_64-linux-gnu/libopencv_videostab.so.2.4.8', needed by`/home/henry/catkin_ws/devel/lib/rossumo/sumo_prompt.exe'.  Stop.

Do you know how to install libopencv_videostab library on ubuntu 14.04?

**Comment by arnaud-ramey** [comment]
That is curious, OpenCV is find_package'd and thus the linked libraries should be the ones you have installed. How did you install OpenCV, stand alone package, package embedded in ROS, or compiled from sources?
In my case, I have installed the version embedded in ROS:
ros-kinetic-vision-opencv

Can you please also determine the CMake script that is called to find OpenCV?
In my case:
/opt/ros/kinetic/share/OpenCV-3.1.0-dev/OpenCVConfig.cmake

**Comment by kaishijeng** [comment]
My ROS is indigo, not kinetic which may be the issue.
Will try  kinetic to see the issue goes away

Thanks

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by arnaud-ramey** [comment]
Well, that's curious anyway, the package is compiled with groovy in Travis, and kinetic on my computer. Keep me updated. If this doesn't work, we can change some Flags in the cmakelist so that only the required modules are loaded.

**Comment by kaishijeng** [comment]
I can't install kinetic because my system is ubuntu 14.04. Only Indigo is available in 14.04.
Can you change flags to avoid using libopencv_videostab.so?

Thanks

**Comment by kaishijeng** [comment]
Arnaud,

  I have upgraded system to ubuntu 16 and installed ros kinetic distribution into it.
Also install your rossumo and compile OK. Can you provide me an  instruction to verify rossumo function with my jump sumo?

Thanks

**Comment by arnaud-ramey** [comment]
Hey, good news. Check out the README for basic instructions. 
To launch the Sumo driver:
$ roslaunch rossumo rossumo.launch
To launch remote control of the Sumo thanks to a USB joystick:
$ roslaunch rossumo joy_teleop.launch
Keep me updated.

**Comment by kaishijeng** [comment]
I am able to  run roslaunch rossumo rossumo.launch and use rostopic pub /rossumo1/anim std_msgs/String "spin" to have sumo car to spin. So rossumo works properly in my system.
Can you provide an example of how to specify the parameter of (m/s, rad/s) for cmd_vel below:
      cmd_vel [geometry_msgs::Twist, (m/s, rad/s)]

Is the following command with parameter OK:
rostopic pub /rossumo1/cmd_vel geometry_msgs/Twist '[10]' '[10]' 

I don't have USB joystick. Instead, I run keyboard_teleop.launch, but there is an error with it.
Does keyboard_teleop.launch work?

Thanks

**Comment by arnaud-ramey** [comment]
In a terminal, type

```
rostopic pub /rossumo1/cmd_vel geometry_msgs/Twist '[TAB]
```

without forgetting the baquote `'`, and your terminal will automatically fill a skeleton of message. 

For the keyboard teleop, please paste the error and I'll look at it. From what I recall, we make use of a generic keyboard teleop driver.

**Comment by arnaud-ramey** [comment]
Hello,
Was the problem solved? Can I close the issue?
Cheers

**Comment by arnaud-ramey** [comment]
I consider the issue closed. Keep me updated if you still have problems.
