### ISSUE TITLE
Error rossumo

### ISSUE THREAD

**Issue by rohan14157** [arnaud-ramey/rossumo#3]
I am having the following error while running catkin_make --only-pkg-with-deps rossumo -DARDRONESDK3_PATH=~/out/Unix-base/staging/

make[2]: *** [rossumo/src/CMakeFiles/rossumo.exe.dir/rossumo.cpp.o] Error 1
make[1]: *** [rossumo/src/CMakeFiles/rossumo.exe.dir/all] Error 2

**Comment by arnaud-ramey** [comment]
Hi,
Thanks for your feedback.
Can you attach post the full output of catkin_make?
Thanks!

**Comment by rohan14157** [comment]
Base path: /home/rohan/Desktop/rossumo_ws
Source space: /home/rohan/Desktop/rossumo_ws/src
Build space: /home/rohan/Desktop/rossumo_ws/build
Devel space: /home/rohan/Desktop/rossumo_ws/devel
Install space: /home/rohan/Desktop/rossumo_ws/install
Whitelisted packages: rossumo
####
#### Running command: "make cmake_check_build_system" in "/home/rohan/Desktop/rossumo_ws/build"
####
####
#### Running command: "make -j4 -l4" in "/home/rohan/Desktop/rossumo_ws/build"
####
[ 25%] [ 50%] Building CXX object rossumo/src/CMakeFiles/light_sumo_test.exe.dir/light_sumo_test.cpp.o
Building CXX object rossumo/src/CMakeFiles/rossumo.exe.dir/rossumo.cpp.o
[ 75%] [100%] Built target sumo_teleop_joy.exe
Building CXX object rossumo/src/CMakeFiles/sumo_prompt.exe.dir/sumo_prompt.cpp.o
In file included from /home/rohan/Desktop/rossumo_ws/src/rossumo/src/light_sumo_test.cpp:25:0:
/home/rohan/Desktop/rossumo_ws/src/rossumo/include/rossumo/light_sumo.h:33:28: fatal error: libARSAL/ARSAL.h: No such file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.
In file included from /home/rohan/Desktop/rossumo_ws/src/rossumo/src/rossumo.cpp:23:0:
/home/rohan/Desktop/rossumo_ws/src/rossumo/include/rossumo/light_sumo.h:33:28: fatal error: libARSAL/ARSAL.h: No such file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.
In file included from /home/rohan/Desktop/rossumo_ws/src/rossumo/src/sumo_prompt.cpp:25:0:
/home/rohan/Desktop/rossumo_ws/src/rossumo/include/rossumo/light_sumo.h:33:28: fatal error: libARSAL/ARSAL.h: No such file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.
make[2]: *** [rossumo/src/CMakeFiles/light_sumo_test.exe.dir/light_sumo_test.cpp.o] Error 1
make[1]: *** [rossumo/src/CMakeFiles/light_sumo_test.exe.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: make[2]: *** [rossumo/src/CMakeFiles/rossumo.exe.dir/rossumo.cpp.o] Error 1
*** [rossumo/src/CMakeFiles/sumo_prompt.exe.dir/sumo_prompt.cpp.o] Error 1
make[1]: *** [rossumo/src/CMakeFiles/sumo_prompt.exe.dir/all] Error 2
make[1]: *** [rossumo/src/CMakeFiles/rossumo.exe.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by arnaud-ramey** [comment]
Hello, 
It looks like CMake cannot find ARDroneSDK3.
Did you download and install ARDroneSDK3 according to the instructions detailed in the README?
In any case, I've updated the lib to make it compatible with the latest version of ARDroneSDK3, v3.1.0.13.
Keep me updated!

**Comment by rohan14157** [comment]
Hello,
After the update you made in the library i was able to build it.
Now when I the command :  roslaunch rossumo rossumo.launch 

I am getting the following output continuously : 

rohan@rohan-HP-15-Notebook-PC:~/Desktop/rossumo_ws$ roslaunch rossumo rossumo.launch
... logging to /home/rohan/.ros/log/d770795a-d959-11e6-bea2-90489a8da403/roslaunch-rohan-HP-15-Notebook-PC-3755.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rohan-HP-15-Notebook-PC:60469/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rossumo1/driver/camera_calibration_camname: head_camera
 * /rossumo1/driver/camera_calibration_filename: /home/rohan/Deskt...
 * /rossumo1/driver/discovery_port: 44444
 * /rossumo1/driver/ip_address: 192.168.2.1
 * /rossumo1/driver/max_vel_ang: 50
 * /rossumo1/driver/max_vel_lin: 50
 * /rosversion: 1.11.20

NODES
  /rossumo1/
    driver (rossumo/rossumo.exe)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[rossumo1/driver-1]: started with pid [3773]
[ INFO] [1484289384.610289319]: rossumo '//rossumo1': IP:192.168.2.1:44444, max velocities:50, 50
[ INFO] [1484289384.616932732]: Succesfully read camera 'head_camera' in camera_calibration file '/home/rohan/Desktop/rossumo_ws/src/rossumo/data/sumo_camera_parameters.yaml'
[INF] rossumo | 12:06:24:838 | connect:121 - -- Jumping Sumo Piloting --
[INF] rossumo | 12:06:24:838 | connect:124 - - init discovey device ... 
[INF] rossumo | 12:06:24:838 | connect:134 - ARDISCOVERY_Device_InitWifi ...
[INF] rossumo | 12:06:24:838 | connect:155 - - delete discovey device ... 
[INF] rossumo | 12:06:24:838 | connect:175 - - set Video callback ... 
[INF] rossumo | 12:06:24:838 | connect:180 - Connecting ...
[INF] rossumo | 12:06:24:838 | stateChanged:399 - stateChanged newState: 1='STARTING' .....
[INF] ARCONTROLLER_Network | 12:06:24:838 | ARCONTROLLER_Network_GetAvailableSocketPort:110 - d2c_port port: 51534
[INF] ARCONTROLLER_Stream2 | 12:06:24:838 | ARCONTROLLER_Stream2_Open_Socket:124 - udp local port stream: 51900
[INF] ARCONTROLLER_Stream2 | 12:06:24:838 | ARCONTROLLER_Stream2_Open_Socket:124 - udp local port control: 55912
commandReceived(102 = 'COMMONSTATE_CURRENTDATECHANGED')
commandReceived(103 = 'COMMONSTATE_CURRENTTIMECHANGED')
commandReceived(92 = 'SETTINGSSTATE_PRODUCTNAMECHANGED')
commandReceived(94 = 'SETTINGSSTATE_PRODUCTSERIALHIGHCHANGED')
commandReceived(95 = 'SETTINGSSTATE_PRODUCTSERIALLOWCHANGED')
commandReceived(93 = 'SETTINGSSTATE_PRODUCTVERSIONCHANGED')
commandReceived(97 = 'SETTINGSSTATE_AUTOCOUNTRYCHANGED')
commandReceived(96 = 'SETTINGSSTATE_COUNTRYCHANGED')
commandReceived(181 = 'NETWORKSETTINGSSTATE_WIFISELECTIONCHANGED')
commandReceived(187 = 'AUDIOSETTINGSSTATE_MASTERVOLUMECHANGED')
volumeChanged(87)
commandReceived(115 = 'WIFISETTINGSSTATE_OUTDOORSETTINGSCHANGED')
commandReceived(196 = 'VIDEOSETTINGSSTATE_AUTORECORDCHANGED')
commandReceived(90 = 'SETTINGSSTATE_ALLSETTINGSCHANGED')
commandReceived(132 = 'ARLIBSVERSIONSSTATE_DEVICELIBARCOMMANDSVERSION')
commandReceived(99 = 'COMMONSTATE_BATTERYSTATECHANGED')
batteryChanged(57%)
commandReceived(168 = 'PILOTINGSTATE_POSTURECHANGED')
postureChanged(1)
commandReceived(171 = 'ANIMATIONSSTATE_JUMPLOADCHANGED')
commandReceived(173 = 'ANIMATIONSSTATE_JUMPMOTORPROBLEMCHANGED')
commandReceived(107 = 'COMMONSTATE_PRODUCTMODEL')
commandReceived(142 = 'CHARGERSTATE_CHARGINGINFO')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(135 = 'ANIMATIONSSTATE_LIST')
commandReceived(98 = 'COMMONSTATE_ALLSTATESCHANGED')
[INF] rossumo | 12:06:25:570 | stateChanged:399 - stateChanged newState: 2='RUNNING' .....
[INF] rossumo | 12:06:25:571 | enable_pic_decoding:356 - - send StreamingVideoEnable ... 
[INF] rossumo | 12:06:25:571 | disable_pic_decoding:366 - - send StreamingVideoDisable ... 
commandReceived(106 = 'COMMONSTATE_SENSORSSTATESLISTCHANGED')
commandReceived(195 = 'MEDIASTREAMINGSTATE_VIDEOENABLECHANGED')
commandReceived(178 = 'MEDIARECORDSTATE_VIDEOSTATECHANGEDV2')
commandReceived(176 = 'MEDIARECORDSTATE_VIDEOSTATECHANGED')
commandReceived(169 = 'PILOTINGSTATE_ALERTSTATECHANGED')
alertChanged(0)
commandReceived(100 = 'COMMONSTATE_MASSSTORAGESTATELISTCHANGED')
commandReceived(101 = 'COMMONSTATE_MASSSTORAGEINFOSTATELISTCHANGED')
commandReceived(195 = 'MEDIASTREAMINGSTATE_VIDEOENABLECHANGED')
commandReceived(186 = 'NETWORKSTATE_LINKQUALITYCHANGED')
link_qualityChanged(1)
commandReceived(105 = 'COMMONSTATE_WIFISIGNALCHANGED')
commandReceived(195 = 'MEDIASTREAMINGSTATE_VIDEOENABLECHANGED')
commandReceived(105 = 'COMMONSTATE_WIFISIGNALCHANGED')
commandReceived(105 = 'COMMONSTATE_WIFISIGNALCHANGED')
commandReceived(105 = 'COMMONSTATE_WIFISIGNALCHANGED')
commandReceived(105 = 'COMMONSTATE_WIFISIGNALCHANGED')
commandReceived(100 = 'COMMONSTATE_MASSSTORAGESTATELISTCHANGED')
commandReceived(101 = 'COMMONSTATE_MASSSTORAGEINFOSTATELISTCHANGED')
commandReceived(105 = 'COMMONSTATE_WIFISIGNALCHANGED')

**Comment by arnaud-ramey** [comment]
This looks good! You should try moving around the robot using the keyboard or a joypad, or check out the camera feedback: check the README for more details. I consider the issue closed.
Cheers
