### ISSUE TITLE
Unable to control the bot using keyboard_teleop

### ISSUE THREAD

**Issue by rohan14157** [arnaud-ramey/rossumo#4]
Hi

I am unable to control the bot using the using the keyboard_teleop.
Pressing the keys i u o etc does not move the bot

Thank You
Rohan Tiwari

**Comment by arnaud-ramey** [comment]
Hi,
Thanks for the feedback.
You were right, the launcher had errors in its configuration.
Can you try again with the latest commits please?

Cheers

**Comment by arnaud-ramey** [comment]
No feedback for 9 months -> closed. Tell me if you still have issues.
