### ISSUE TITLE
cannot launch rossumo.exe

### ISSUE THREAD

**Issue by LeanderCoevoet** [arnaud-ramey/rossumo#6]
I am having the following error while running roslaunch rossumo rossumo.launch

ERROR: cannot launch node of type [rossumo/rossumo.exe]: can't locate node [rossumo.exe]  in package [rossumo]

The full output is if you are interested:
... logging to /home/leander/.ros/log/3df5b236-b2b6-11e7-80dc-40e2309f8f2b/roslaunch-leander-12401.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://leander:46794/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rossumo1/driver/camera_calibration_camname: head_camera
 * /rossumo1/driver/camera_calibration_filename: /home/leander/cat...
 * /rossumo1/driver/discovery_port: 44444
 * /rossumo1/driver/ip_address: 192.168.2.1
 * /rossumo1/driver/max_vel_ang: 50
 * /rossumo1/driver/max_vel_lin: 50
 * /rosversion: 1.11.21

NODES
  /rossumo1/
    driver (rossumo/rossumo.exe)

auto-starting new master
process[master]: started with pid [12413]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3df5b236-b2b6-11e7-80dc-40e2309f8f2b
process[rosout-1]: started with pid [12426]
started core service [/rosout]
ERROR: cannot launch node of type [rossumo/rossumo.exe]: can't locate node [rossumo.exe] in package [rossumo]

**Comment by arnaud-ramey** [comment]
Problem solved?

**Comment by LeanderCoevoet** [comment]
Yes and sorry for bothering you

**Comment by jprojs** [comment]
Hi, how did you solved it?

**Comment by arnaud-ramey** [comment]
It looks like the package wasn't compiled before the launch file was launched.
Check the "Installation" paragraph in the README file.

**Comment by jprojs** [comment]
You should explain better the instructions in README file
