### ISSUE TITLE
The specified base path "/home/user/rossumo" contains a package but "catkin_make" must be invoked in the root of workspace

### ISSUE THREAD

**Issue by fotiDim** [arnaud-ramey/rossumo#7]
I am getting this error when running to run catkin_make:
`The specified base path "/home/fotidim/rossumo" contains a package but "catkin_make" must be invoked in the root of workspace`

I just install the ARSDK then cloned rossumo and tried to run `catkin_make --only-pkg-with-deps rossumo`

**Comment by arnaud-ramey** [comment]
Did you install ROS properly?
If no, check [here](http://wiki.ros.org/kinetic/Installation/Ubuntu) then [here](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment).

If yes, make sure you cloned the rossumo repo in the "src" folder of your workspace.

**Comment by rizakurt** [comment]
![ekran goruntusu - 2017-11-24 17-39-31](https://user-images.githubusercontent.com/33955782/33214896-ba3e929e-d13e-11e7-9f36-2d84617b9aaf.png)

**Comment by rizakurt** [comment]
I have this problem

**Comment by fotiDim** [comment]
I got it to work. I created a Pull Request to improve the installation documentation: #8

**Comment by fotiDim** [comment]
I think this should be closed. @rmeka66 check the new readme instructions.
